### ISSUE TITLE
Some confusions about the efficiency

### ISSUE THREAD

**Issue by renaomin** [AndreiChertkov/teneva#3]
Hi @AndreiChertkov,

Thanks for developing and sharing the toolbox. As a black-box optimizer, do you think its computation speed is competable to other current gradient-free optimizer? If I have an MPC problem and want to solve it by teneva(or jax version) at a high frequency (e.g., 10~100HZ), is it possible?. Another question is that how to choose the fixed TT-ranks? 

Best,
@renaomin

**Comment by AndreiChertkov** [comment]
Dear @renaomin,

thank you for your interest in our software product! ;)

Regarding the optimization, I suggest you look at our repositories [TTOpt](https://github.com/AndreiChertkov/ttopt) and [PROTES](https://github.com/anabatsh/PROTES) with the implementation of gradient-free optimizers based on the TT-decomposition. The repositories also contain links to our papers that provide comparison results with several other optimization methods (GA, ES, etc.) for various benchmarks (including optimal control problems for PROTES).

Concerning the problem of choice of the constant TT-rank, I suppose you mean (?) the TT-cross method (i.e., function "cross"), since in the case of other functions (including the TT-ALS method), the TT-rank is assumed to be constant. In the case of the "cross" function, to select a constant TT-rank, it is enough to specify an argument "dr_max" equal to 0 (please note that in this case, you should specify the initial approximation "Y0" having the required constant TT-rank).

Best regards,
Andrei.
